RatSaturn/grace-shopper

.travis.yml, package.json, public/index.html
=> refactor: updated travis file with heroku API key, as well as title in html file

public/index.html
=> fix: fixed title to bookstack

public/index.html, script/seed.js, server/db/models/book.js, server/db/models/index.js
=> chore: added book model and seed of two books

server/api/books.js, server/api/books.spec.js, server/api/index.js
=> chore: added book api route and test spec

script/seed.js, server/db/models/index.js, server/db/models/order.js
=> chore: Updated pseudo seed and order api

client/components/AllBooks.js, client/components/BookComponent.js, client/components/index.js, client/components/navbar.js, client/routes.js, public/style.css
---
Implemented basic front-end, including dropdown menu, dynamic routing and All Books view with dummy data.
=> All books component

client/components/SingleBook.js, client/components/index.js, client/routes.js, client/store/index.js, client/store/singleBook.js
=> chore: Single book view component and reducer

.babelrc, client/components/BookComponent.js, client/components/BookComponent.spec.js, client/store/singleBook.js, package-lock.json, package.json
=> chore: created book component test spec

server/db/models/author.js, server/db/models/author.spec.js, server/db/models/genre.js, server/db/models/genre.spec.js, server/db/models/index.js, server/db/models/staff.js, server/db/models/staff.spec.js
=> chore: updated models and test specs

client/components/AllBooks.js, client/components/AllBooks.spec.js
=> chore: test created for allbooks component

script/seed.js, server/api/books.spec.js, server/db/models/book.js, server/db/models/index.js
=> Fix book model

script/seed.js
=> init imageUrl with defaultValue and random price if not exists

client/components/AllBooks.js, client/components/AllBooks.spec.js, client/components/SingleBook.js, client/components/SingleBook.spec.js, client/store/singleBook.js, server/api/authors.js, server/api/books.js, server/api/books.spec.js, server/api/genres.js, server/api/index.js, server/api/staff.js
* [X ] added unit tests (or none needed)
---
Implemented back-end routes for the following: all staff, one book by ID, single staff by ID, findByAuthor, genres
Implemented front-end for Single Book
=> Api routes

server/api/books.js, server/db/models/booksForOrders.js, server/db/models/order.js
* [ x] written relevant docs (or none needed)
* [x ] referenced any relevant issues (or none exist)
---
=> Instance and class methods

server/api/orders.js, server/db/models/order.js
back-end for cart (get '/api/orders/cart' and post '/api/orders/cart/update' with {bookId, quantity}) completed
=> Api orders

client/components/Cart.js, client/components/SingleBook.js, client/store/cart.js
=> refactor: update store to optimize storage and speed

client/components/AllBooks.js, client/components/CartItem.js, client/components/SingleBook.js, client/store/cart.js
…ate in singleBook component
---
=> fix: connected quantity dropdown to actual value, corrected allBooks

client/components/SingleBook.js, client/store/cart.js, package-lock.json
=> fix: edited thunk to pass book from server (to access booksForOrder)

client/components/AllBooks.js, client/store/cart.js
=> fix: connected database to addCart action creator & thunk

client/components/landing-page/book-card.js, client/components/landing-page/new-arrivals.js, client/components/navbar.js
=> fix: corrected displayed price on book card

client/components/navbar.js
=> fix: wrapped button in Link component from react-router-dom on navbar

client/components/Checkout.js
=> implemented checkout rerouting

client/components/CartItem.js, client/store/cart.js
=> fix: cart store copyOfBooks bug

client/components/SingleBook.js
=> fix: addItems fixed

client/components/Checkout.js, client/components/ReviewCopy.js, client/components/ReviewOrder.js, client/components/landing-page/hero-component.js
* [ x] written relevant docs (or none needed)
* [x ] referenced any relevant issues (or none exist)
---
=> Style review
